apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: test-cluster
spec:
  servers: 1
  agents: 1
  token: test
  version: v1.27.11-k3s1
  clusterCIDR: 10.30.0.0/16
  serviceCIDR: 10.31.0.0/16
    #clusterDNS: 10.30.0.10
  serverArgs:
  - "--write-kubeconfig-mode=777"
  - "--disable=servicelb"
  - "--disable=traefik"
  - "--disable-cloud-controller"
  - "--disable-network-policy
    #  expose:
    #ingress:
    #  enabled: true
    #  ingressClassName: "nginx"

